# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  IISWebsiteName: 'BillPayment'

resources:
  pipelines:
    - pipeline: buildPipeline
      project: 'BillPayment'
      source: 'Build Pipeline'
      branch: 'main'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'
    pool:
      vmImage: 'windows-latest'

    jobs:
      - deployment: DeployWebsite
        displayName: 'Deploy website'
        environment: 'DEVWEBTEST01'  # This matches your agent name
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none

                - download: buildPipeline
                  name: DownloadBuildArtifacts
                  displayName: 'Download Build Artifacts'
                  artifact: 'BillingPaymentArtifact'

                - task: IISWebAppManagementOnMachineGroup@0
                  name: StopIISWebsite
                  displayName: 'Stop IIS Website'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StopWebsite'
                    StartStopWebsiteName: '${{ variables.IISWebsiteName }}'

                - task: IISWebAppDeploymentOnMachineGroup@0
                  name: 'DeployIISWebsite'
                  displayName: 'Deploy IIS Website'
                  inputs:
                    WebSiteName: '${{ variables.IISWebsiteName }}'
                    Package: '$(Pipeline.Workspace)\buildPipeline\BillingPaymentArtifact\BillingPayment'
                    TakeAppOfflineFlag: true

                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StartIISWebsite'
                  displayName: 'Start IIS Website'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StartWebsite'
                    StartStopWebsiteName: '${{ variables.IISWebsiteName }}'