# Azure DevOps Pipeline for Deploying BillPayment Application to IIS

trigger: none

variables:
  IISWebsiteName: 'Default Web Site'
  IISVirtualAppName: 'BillPayment'

resources:
  pipelines:
    - pipeline: buildPipeline
      project: 'BillPayment'
      source: 'Build Pipeline'
      branch: 'main'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'
    pool:
      vmImage: 'windows-latest'

    jobs:
      - deployment: DeployWebsite
        displayName: 'Deploy website'
        environment: 'DEVWEBTEST01'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none

                - download: buildPipeline
                  name: DownloadBuildArtifacts
                  displayName: 'Download Build Artifacts'
                  artifact: 'BillingPaymentArtifact'

                - task: IISWebAppDeploymentOnMachineGroup@0
                  name: DeployIISWebsite
                  displayName: 'Deploy IIS Website'
                  inputs:
                    WebSiteName: '${{ variables.IISWebsiteName }}'
                    VirtualApplication: '${{ variables.IISVirtualAppName }}'
                    Package: '$(Pipeline.Workspace)\buildPipeline\BillingPaymentArtifact\BillingPayment'
                    TakeAppOfflineFlag: true
